### ISSUE TITLE
6.1 Make receving Linked Data Notifications in line with the use-case of COAR?

### ISSUE THREAD

**Issue by phochste** [MellonScholarlyCommunication/spec-orchestrator#8]
Currently the spec says:

- as:Create
- as:Announce
- as:Update
- as:Delete

COAR requires:

- as:Offer
- as:Undo
- as:Accept
- as:Reject
- as:Announce

**Comment by mielvds** [comment]
We'll find out once https://github.com/MellonScholarlyCommunication/spec-notifications gets some body (working on that soon)

That said, I'm starting to wonder whether not the whole list of possible notifications in the network is of interest to the Orchestrator.

**Comment by mielvds** [comment]
Closed in favor of https://github.com/MellonScholarlyCommunication/spec-notifications/issues/1
